### PR TITLE
Fix scrolling on `g g` and `G`

### LINKED ISSUE #134: `gg` and `G` no longer working in `jupyterlab 4.1.0`
## Description

After updating from `jupyterlab 4.0.11` to `jupyterlab 4.1.0`, the commands `gg` and `G` to navigate to the top/bottom cell of the notebook in jupyter mode no longer seem to work. Going back to `jupyterlab 4.0.11` both `gg` and `G` work as expected.

Can anybody else confirm this?

## Context

- Python version: 3.12.1
- jupyterlab-vim version: 4.1.0
- Operating System and its version: Linux Manjaro
- Browser and its version: Firefox 122.0-1

### PR DESCRIPTION
**Pull request by krassowski**
Closes #134

To add more context, we should make this change anyways, because otherwise scrolling would not work in the `full` windowing mode.

### CODE REVIEW

**Review by lukashergt — APPROVED** [review]
I've tried out the binder. `gg` and `G` working as expected, jumping to top/bottom cell respectively and the view jumps, too, i.e. the scrolling seems to be working now. Thanks for the speedy fix @krassowski!

**Comment by ianhi** [comment]
This does indeed fix the scrolling but I think it's doing something weird to selection state of the cell. When i do this I have to hit `enter` twice in order to get to cell edit (vim normal) mode. In contrast when in jupyter command mode if I move up a cell with `j` then it only takes one `enter` press to accomplish the same.

**Review by ianhi — CHANGES_REQUESTED** [review]
I'd like to figure out the best way to get us into jupyter-command-mode with the scrolled to cell one enter press away from being in edit mode. I have one suggestion i added to the review but im not sure it's the best way. I wish there was an option in `scrollToCell` that allowed you choose whether to enter edit mode.

File: src/labCommands.ts [hunk 1]
```diff
@@ -265,10 +262,8 @@ export function addNotebookCommands(
           content.activeCellIndex = current.content.widgets.length - 1;
           content.deselectAll();
           if (content.activeCell !== null) {
-            ElementExt.scrollIntoViewIfNeeded(
-              content.node,
-              content.activeCell.node
-            );
+            // note: using `scrollToItem` because `scrollToCell` changes mode (activate the cell)
+            content.scrollToItem(content.activeCellIndex, 'smart');
```
Comment (ianhi) [inline src/labCommands.ts:266]: One option to fix the cell not being properly selected. Seems a bit silly, but i tried using `content.select` after scrollToItem and it didn't work

```suggestion
            content.scrollToCell(content.activeCell, 'smart').then((value) => {
                commands.execute('notebook:enter-command-mode');
              }
            );
```

Comment (krassowski) [reply src/labCommands.ts]: Thank you @ianhi! I pushed [be7c017](https://github.com/jupyterlab-contrib/jupyterlab-vim/pull/137/commits/be7c0178ccbb0c4355c917eff325850a54c8d50b) which solves this problem by focusing the cell explicitly. This is faster than using `scrollToCell` and executing a command because `scrollToCell` will take extra time to change mode, and executing the command will be delayed by one idle cycle which can lead to visual jitter.

Comment (ianhi) [reply src/labCommands.ts]: that looks awesome thank you!

**Review by ianhi — APPROVED** [review]
thanks for the quick follow up fixes @krassowski !
